name: Android Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - uses: actions/checkout@v2

      # 2. Configurar versión de Java
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # 3. Configurar permisos de Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Cachear dependencias de Gradle para optimizar tiempo de build
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # 5. Compilar y generar el paquete .aar
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # 6. Guardar el paquete generado
      - name: Upload AAR/JAR
        uses: actions/upload-artifact@v3
        with:
          name: library-package
          path: app/build/outputs/aar/app-release.aar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - uses: actions/checkout@v2

      # 2. Descargar el Artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: library-package

      # 3. Crear un Release en GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: 'Release v1.0.0'
          draft: false
          prerelease: false

      # 4. Subir el Asset al Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/aar/app-release.aar
          asset_name: app-release.aar
          asset_content_type: application/zip